const images = {
  pet01: require('../../assets/images/pet_01.png'),
  pet02: require('../../assets/images/pet_02.png'),
  pet03: require('../../assets/images/pet_03.png'),
  pet04: require('../../assets/images/pet_04.png'),
  pet05: require('../../assets/images/pet_05.png'),
  pet06: require('../../assets/images/pet_06.png'),
  pet07: require('../../assets/images/pet_07.png'),
  pet08: require('../../assets/images/pet_08.png'),
  pet09: require('../../assets/images/pet_09.png'),
  pet10: require('../../assets/images/pet_10.png'),
  petOwner01: require('../../assets/images/pet_owner_01.png'),
  petOwner02: require('../../assets/images/pet_owner_02.png'),
  petOwner03: require('../../assets/images/pet_owner_03.png'),
  petOwner04: require('../../assets/images/pet_owner_04.png'),
  petOwner05: require('../../assets/images/pet_owner_05.png'),
  petOwner06: require('../../assets/images/pet_owner_06.png'),
  petOwner07: require('../../assets/images/pet_owner_07.png'),
  petOwner08: require('../../assets/images/pet_owner_08.png'),
  petOwner09: require('../../assets/images/pet_owner_09.png'),
  petOwner10: require('../../assets/images/pet_owner_10.png'),
};

const petData = [
  {
    id: '1',
    petOwnerImage: images.petOwner01,
    ownerName: 'Shania Mu',
    petImage: images.pet01,
    petName: 'Nala Daisy',
    petType: 'Dog',
    isFavorite: true,
  },
  {
    id: '2',
    petOwnerImage: images.petOwner02,
    ownerName: 'Nobara Lie',
    petImage: images.pet02,
    petName: 'Eve Shine',
    petType: 'Cat',
    isFavorite: false,
  },
  {
    id: '3',
    petOwnerImage: images.petOwner03,
    ownerName: 'Akasa Yumi',
    petImage: images.pet03,
    petName: 'Max Lucky',
    petType: 'Dog',
    isFavorite: true,
  },
  {
    id: '4',
    petOwnerImage: images.petOwner04,
    ownerName: 'Yuki Takahashi',
    petImage: images.pet04,
    petName: 'Rexy Power',
    petType: 'Cat',
    isFavorite: false,
  },
  {
    id: '5',
    petOwnerImage: images.petOwner05,
    ownerName: 'Li Wei',
    petImage: images.pet05,
    petName: 'Bella Joy',
    petType: 'Dog',
    isFavorite: true,
  },
  {
    id: '6',
    petOwnerImage: images.petOwner06,
    ownerName: 'Oliver Brown',
    petImage: images.pet06,
    petName: 'Whiskers',
    petType: 'Cat',
    isFavorite: false,
  },
  {
    id: '7',
    petOwnerImage: images.petOwner07,
    ownerName: 'Hiroshi Sato',
    petImage: images.pet07,
    petName: 'Milo',
    petType: 'Dog',
    isFavorite: true,
  },
  {
    id: '8',
    petOwnerImage: images.petOwner08,
    ownerName: 'Jia Li',
    petImage: images.pet08,
    petName: 'Kiki',
    petType: 'Cat',
    isFavorite: false,
  },
  {
    id: '9',
    petOwnerImage: images.petOwner09,
    ownerName: 'Emily Smith',
    petImage: images.pet09,
    petName: 'Fluffy',
    petType: 'Dog',
    isFavorite: true,
  },
  {
    id: '10',
    petOwnerImage: images.petOwner10,
    ownerName: 'Sakura Fujiwara',
    petImage: images.pet10,
    petName: 'Coco',
    petType: 'Cat',
    isFavorite: false,
  },
];

export default petData;
